knp_gaufrette:
  stream_wrapper: ~
  adapters:
    document_adapter:
      aws_s3:
        service_id: 'acme.aws_s3.client'
        bucket_name: '%env(AWS_S3_BUCKET_NAME)%'
        detect_content_type: true
        options:
          create: true
          directory: document
  filesystems:
    document_fs:
      adapter:    document_adapter


