# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Service\:
        resource: '../src/Service'
        autowire: false

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    acme.aws_s3.client:
        public: true
        class: Aws\S3\S3Client
        factory: [Aws\S3\S3Client, 'factory']
        arguments:
            - version: latest
              region: '%env(AWS_S3_REGION)%'
              credentials:
                  key: '%env(AWS_S3_KEY)%'
                  secret: '%env(AWS_S3_SECRET)%'

    App\Service\S3Uploader:
        public: true
        class: App\Service\S3Uploader
        arguments:
            - '@acme.aws_s3.client'
            - '%env(AWS_S3_BUCKET_NAME)%'
            - '%env(AWS_S3_KEY)%'
            - '%env(AWS_S3_REGION)%'
            - '%env(AWS_S3_SECRET)%'

    App\Service\S3Copier:
        public: true
        class: App\Service\S3Copier
        arguments:
            - '@acme.aws_s3.client'
            - '%env(AWS_S3_BUCKET_NAME)%'
            - '%env(AWS_S3_KEY)%'
            - '%env(AWS_S3_REGION)%'
            - '%env(AWS_S3_SECRET)%'

    App\UseCase\RenamePhoto:
        public: true
        class: App\UseCase\RenamePhoto
        arguments:
            - '@logger'
            - '@App\Service\S3Copier'


